(() => {
  if (window.__pobPolicyRunner || window.top !== window) return; window.__pobPolicyRunner=true;
  const API=window.POB_POLICY;if(!API)return;
  let cancelled=false, stepping=false;
  const load=async()=> (await chrome.storage.local.get("run")).run||null;
  const save=async(patch)=>{const run=await load();const next={...(run||{}),...patch};await chrome.storage.local.set({run:next});render(next);return next;};
  const send=(message)=>new Promise((resolve,reject)=>chrome.runtime.sendMessage(message,(response)=>chrome.runtime.lastError?reject(new Error(chrome.runtime.lastError.message)):resolve(response)));
  const api=async(path,body)=>{const res=await send({type:"policy-api",path,method:"POST",body});if(!res?.ok)throw new Error(res?.error||"Request failed");return res.data;};
  let panel,status,count,pause,stop;
  function ui(){if(panel&&document.body.contains(panel))return;panel=document.createElement("aside");panel.id="pob-policy-runner";panel.style.cssText="position:fixed;right:18px;bottom:18px;z-index:2147483647;width:320px;padding:15px;border:1px solid #dadce0;border-radius:8px;background:#fff;color:#202124;box-shadow:0 8px 30px #0003;font:13px/1.45 Arial,sans-serif";panel.innerHTML='<div style="display:flex;gap:8px;align-items:center"><b style="flex:1">Policy Violation</b><span id="pv-count"></span></div><p id="pv-status" style="min-height:38px;white-space:pre-wrap;color:#5f6368"></p><div style="display:flex;gap:8px"><button id="pv-pause" style="flex:1;padding:8px">Pause</button><button id="pv-stop" style="flex:1;padding:8px;color:#b3261e">Stop</button></div>';document.body.appendChild(panel);status=panel.querySelector("#pv-status");count=panel.querySelector("#pv-count");pause=panel.querySelector("#pv-pause");stop=panel.querySelector("#pv-stop");pause.onclick=async()=>{const run=await load();cancelled=true;const next=await save({paused:!run.paused});status.textContent=next.paused?"Paused. Current report remains reserved.":"Resuming…";if(!next.paused){cancelled=false;void step();}};stop.onclick=async()=>{cancelled=true;const run=await load();if(run?.current)await api("/api/public/policy-extension/release",{itemId:run.current.itemId,claimToken:run.current.claimToken,error:"Run stopped by operator."}).catch(()=>{});await chrome.storage.local.remove("run");status.textContent="Stopped. Current report returned to the queue.";pause.disabled=true;stop.disabled=true;};}
  function render(run){ui();count.textContent=`${run?.done||0}/${run?.total||0} done${run?.failed?` · ${run.failed} failed`:""}`;pause.textContent=run?.paused?"Resume":"Pause";}
  function log(text){ui();status.textContent=text;}
  function fresh(){setTimeout(()=>location.href=window.POB_POLICY_CONFIG.formUrl,700);}
  async function step(){if(stepping)return;stepping=true;try{let run=await load();if(!run?.active)return;render(run);if(run.paused)return log("Paused.");if(run.stage==="awaiting"&&API.confirmed())return confirm(run);if(!run.current){log("Claiming the next prepared report…");const claimToken=crypto.randomUUID();let data;try{data=await api("/api/public/policy-extension/next",{orderId:run.orderId,claimToken,skipIds:run.skipIds||[]});}catch(error){log(`${error.message}\nRetrying in 20 seconds…`);await API.sleep(20000);stepping=false;return step();}if(data.done){await chrome.storage.local.remove("run");return log(`Run complete. ${data.progress?.submitted??run.done??0} submitted${data.skipped?`, ${data.skipped} failed after all retries (still pending)`:""}.`);}run=await save({current:data,stage:"claimed",rounds:0,done:data.progress?.submitted??run.done??0,total:data.progress?.total||run.total});}
    const stored=await chrome.storage.local.get("details");const details={...window.POB_POLICY_CONFIG.defaults,...stored.details};if(!details.fullName)return log("Add your full legal name in Settings, then Resume.");log(`Filling ${run.current.primaryPolicy||"policy violation"} report…`);const filled=await API.fill(run.current,details,log);if(!filled.ok)return retryOrSkip(run,`Form fill: ${filled.reason}`);await save({stage:"awaiting"});const delay=Math.max(2,Math.min(60,Number(details.submitDelay)||5));cancelled=false;for(let n=delay;n>0;n--){if(cancelled)return;log(`All required fields verified. Submitting in ${n}s…`);await API.sleep(1000);}const result=await API.submit(log,()=>cancelled);if(!result.ok){if(result.reason==="cancelled")return;if(result.fatal)return log(`Stopped: ${result.reason}\nFix it in Settings, then Resume.`);return retryOrSkip(await load(),result.reason);}await confirm(await load(),result.caseRef);
  }finally{stepping=false;}}
  async function retryOrSkip(run,reason){const rounds=(run.rounds||0)+1;if(rounds<3){await save({rounds,stage:"claimed"});log(`${reason}\nReloading form and retrying this report (round ${rounds+1}/3)…`);return fresh();}log(`${reason}\nFailed after 3 rounds. Skipping to the next report…`);await api("/api/public/policy-extension/release",{itemId:run.current.itemId,claimToken:run.current.claimToken,error:`Extension failed: ${String(reason).slice(0,300)}`}).catch(()=>{});await save({current:null,stage:"idle",rounds:0,failed:(run.failed||0)+1,skipIds:[...(run.skipIds||[]),run.current.itemId]});fresh();}
  async function confirm(run,caseRef=""){if(!run?.current)return;log("Google confirmed. Saving completion…");try{const result=await api("/api/public/policy-extension/confirm",{itemId:run.current.itemId,claimToken:run.current.claimToken,caseRef});const p=result.progress;const next=await save({current:null,stage:"idle",rounds:0,done:p.submitted,total:p.total,sessionDone:(run.sessionDone||0)+1});if(p.ready===0&&p.inProgress===0){await chrome.storage.local.remove("run");return log("Every prepared report is submitted. Run complete.");}log(`✓ Report submitted (${p.submitted}/${p.total} done for this order). ${Math.max(0,p.ready+p.inProgress-(next.skipIds||[]).length)} remaining. Moving to next…`);fresh();}catch(error){log(`Google confirmed, but saving failed: ${error.message}\nDo not resubmit; press Resume to retry saving.`);}}
  chrome.storage.onChanged.addListener((changes,area)=>{if(area==="local"&&changes.run?.newValue?.active&&!changes.run.newValue.paused)void step();});
  const boot=async()=>{const run=await load();if(run?.active){ui();render(run);void step();}};document.readyState==="loading"?document.addEventListener("DOMContentLoaded",boot):void boot();
})();
