/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as XrpuasLogRouteImport } from './routes/xrpuas-log'
import { Route as ProfileSlugIndexRouteImport } from './routes/$profileSlug.index'
import { Route as ProfileSlugReviewSlugRouteImport } from './routes/$profileSlug.$reviewSlug'
import { Route as BenediktHerrmannIndexRouteImport } from './routes/Benedikt-Herrmann.index'
import { Route as BenediktHerrmannSlugRouteImport } from './routes/Benedikt-Herrmann.$slug'
import { Route as BenediktHerrmannIndexInfoRouteImport } from './routes/Benedikt-Herrmann.index-info'
import { Route as JonasWeberIndexRouteImport } from './routes/Jonas-Weber.index'
import { Route as JonasWeberSlugRouteImport } from './routes/Jonas-Weber.$slug'
import { Route as JonasWeberIndexInfoRouteImport } from './routes/Jonas-Weber.index-info'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAfridiRouteImport } from './routes/admin.afridi'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as AdminArchiveRouteImport } from './routes/admin.archive'
import { Route as AdminDmcaRouteImport } from './routes/admin.dmca'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as AdminRobiulRouteImport } from './routes/admin.robiul'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWriteRouteImport } from './routes/admin.write'
import { Route as AfridiIndexRouteImport } from './routes/afridi.index'
import { Route as AfridiSlugRouteImport } from './routes/afridi.$slug'
import { Route as AfridiIndexInfoRouteImport } from './routes/afridi.index-info'
import { Route as ApiAiChatRouteImport } from './routes/api/ai-chat'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppDmcaRouteImport } from './routes/app.dmca'
import { Route as AppGuideRouteImport } from './routes/app.guide'
import { Route as AppPostRouteImport } from './routes/app.post'
import { Route as AppProfilesRouteImport } from './routes/app.profiles'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as RobiulAlamIndexRouteImport } from './routes/robiul-alam.index'
import { Route as RobiulAlamSlugRouteImport } from './routes/robiul-alam.$slug'
import { Route as RobiulAlamIndexInfoRouteImport } from './routes/robiul-alam.index-info'
import { Route as JordanReviewsIndexRouteImport } from './routes/Jordan.reviews.index'
import { Route as JordanReviewsSlugRouteImport } from './routes/Jordan.reviews.$slug'
import { Route as JordanReviewsIndexInfoRouteImport } from './routes/Jordan.reviews.index-info'
import { Route as AdminFakeReviewsIndexRouteImport } from './routes/admin.fake-reviews.index'
import { Route as AdminFakeReviewsOrderIdRouteImport } from './routes/admin.fake-reviews.$orderId'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin.orders.$orderId'
import { Route as AdminPolicyIndexRouteImport } from './routes/admin.policy.index'
import { Route as AdminPolicyOrderIdRouteImport } from './routes/admin.policy.$orderId'
import { Route as AdminPolicyTrainingRouteImport } from './routes/admin.policy.training'
import { Route as AppFakeReviewsIndexRouteImport } from './routes/app.fake-reviews.index'
import { Route as AppFakeReviewsOrderIdRouteImport } from './routes/app.fake-reviews.$orderId'
import { Route as AppOrdersIndexRouteImport } from './routes/app.orders.index'
import { Route as AppOrdersOrderIdRouteImport } from './routes/app.orders.$orderId'
import { Route as AppPolicyIndexRouteImport } from './routes/app.policy.index'
import { Route as AppPolicyOrderIdRouteImport } from './routes/app.policy.$orderId'
import { Route as UHandleIndexRouteImport } from './routes/u.$handle.index'
import { Route as UHandleSlugRouteImport } from './routes/u.$handle.$slug'
import { Route as ApiPublicDmcaConfirmRouteImport } from './routes/api/public/dmca/confirm'
import { Route as ApiPublicDmcaConfirmSingleRouteImport } from './routes/api/public/dmca/confirm-single'
import { Route as ApiPublicDmcaNextBatchRouteImport } from './routes/api/public/dmca/next-batch'
import { Route as ApiPublicDmcaNextSingleRouteImport } from './routes/api/public/dmca/next-single'
import { Route as ApiPublicDmcaOrdersRouteImport } from './routes/api/public/dmca/orders'
import { Route as ApiPublicDmcaReleaseRouteImport } from './routes/api/public/dmca/release'
import { Route as ApiPublicDmcaReleaseSingleRouteImport } from './routes/api/public/dmca/release-single'
import { Route as ApiPublicFakeReviewsCaptureRouteImport } from './routes/api/public/fake-reviews/capture'
import { Route as ApiPublicFakeReviewsDripTickRouteImport } from './routes/api/public/fake-reviews/drip-tick'
import { Route as ApiPublicFakeReviewsSessionRouteImport } from './routes/api/public/fake-reviews/session'
import { Route as ApiPublicPolicyExtensionConfirmRouteImport } from './routes/api/public/policy-extension/confirm'
import { Route as ApiPublicPolicyExtensionNextRouteImport } from './routes/api/public/policy-extension/next'
import { Route as ApiPublicPolicyExtensionOrdersRouteImport } from './routes/api/public/policy-extension/orders'
import { Route as ApiPublicPolicyExtensionReleaseRouteImport } from './routes/api/public/policy-extension/release'
import { Route as ApiPublicProfilesNextTargetRouteImport } from './routes/api/public/profiles/next-target'
import { Route as ApiPublicProfilesOrdersRouteImport } from './routes/api/public/profiles/orders'
import { Route as ApiPublicProfilesSubmitTargetRouteImport } from './routes/api/public/profiles/submit-target'
import { Route as ApiPublicReviewImageSplatRouteImport } from './routes/api/public/review-image/$'
import { Route as ApiPublicUserDmcaConfirmRouteImport } from './routes/api/public/user-dmca/confirm'
import { Route as ApiPublicUserDmcaConfirmSingleRouteImport } from './routes/api/public/user-dmca/confirm-single'
import { Route as ApiPublicUserDmcaNextBatchRouteImport } from './routes/api/public/user-dmca/next-batch'
import { Route as ApiPublicUserDmcaNextSingleRouteImport } from './routes/api/public/user-dmca/next-single'
import { Route as ApiPublicUserDmcaOrdersRouteImport } from './routes/api/public/user-dmca/orders'
import { Route as ApiPublicUserDmcaReleaseRouteImport } from './routes/api/public/user-dmca/release'
import { Route as ApiPublicUserDmcaReleaseSingleRouteImport } from './routes/api/public/user-dmca/release-single'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const XrpuasLogRoute = XrpuasLogRouteImport.update({
  id: '/xrpuas-log',
  path: '/xrpuas-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSlugIndexRoute = ProfileSlugIndexRouteImport.update({
  id: '/$profileSlug/',
  path: '/$profileSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSlugReviewSlugRoute = ProfileSlugReviewSlugRouteImport.update({
  id: '/$profileSlug/$reviewSlug',
  path: '/$profileSlug/$reviewSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const BenediktHerrmannIndexRoute = BenediktHerrmannIndexRouteImport.update({
  id: '/Benedikt-Herrmann/',
  path: '/Benedikt-Herrmann/',
  getParentRoute: () => rootRouteImport,
} as any)
const BenediktHerrmannSlugRoute = BenediktHerrmannSlugRouteImport.update({
  id: '/Benedikt-Herrmann/$slug',
  path: '/Benedikt-Herrmann/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BenediktHerrmannIndexInfoRoute =
  BenediktHerrmannIndexInfoRouteImport.update({
    id: '/Benedikt-Herrmann/index-info',
    path: '/Benedikt-Herrmann/index-info',
    getParentRoute: () => rootRouteImport,
  } as any)
const JonasWeberIndexRoute = JonasWeberIndexRouteImport.update({
  id: '/Jonas-Weber/',
  path: '/Jonas-Weber/',
  getParentRoute: () => rootRouteImport,
} as any)
const JonasWeberSlugRoute = JonasWeberSlugRouteImport.update({
  id: '/Jonas-Weber/$slug',
  path: '/Jonas-Weber/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JonasWeberIndexInfoRoute = JonasWeberIndexInfoRouteImport.update({
  id: '/Jonas-Weber/index-info',
  path: '/Jonas-Weber/index-info',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAfridiRoute = AdminAfridiRouteImport.update({
  id: '/afridi',
  path: '/afridi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArchiveRoute = AdminArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDmcaRoute = AdminDmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRobiulRoute = AdminRobiulRouteImport.update({
  id: '/robiul',
  path: '/robiul',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWriteRoute = AdminWriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => AdminRoute,
} as any)
const AfridiIndexRoute = AfridiIndexRouteImport.update({
  id: '/afridi/',
  path: '/afridi/',
  getParentRoute: () => rootRouteImport,
} as any)
const AfridiSlugRoute = AfridiSlugRouteImport.update({
  id: '/afridi/$slug',
  path: '/afridi/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AfridiIndexInfoRoute = AfridiIndexInfoRouteImport.update({
  id: '/afridi/index-info',
  path: '/afridi/index-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai-chat',
  path: '/api/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDmcaRoute = AppDmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => AppRoute,
} as any)
const AppGuideRoute = AppGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AppRoute,
} as any)
const AppPostRoute = AppPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilesRoute = AppProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const RobiulAlamIndexRoute = RobiulAlamIndexRouteImport.update({
  id: '/robiul-alam/',
  path: '/robiul-alam/',
  getParentRoute: () => rootRouteImport,
} as any)
const RobiulAlamSlugRoute = RobiulAlamSlugRouteImport.update({
  id: '/robiul-alam/$slug',
  path: '/robiul-alam/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RobiulAlamIndexInfoRoute = RobiulAlamIndexInfoRouteImport.update({
  id: '/robiul-alam/index-info',
  path: '/robiul-alam/index-info',
  getParentRoute: () => rootRouteImport,
} as any)
const JordanReviewsIndexRoute = JordanReviewsIndexRouteImport.update({
  id: '/Jordan/reviews/',
  path: '/Jordan/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const JordanReviewsSlugRoute = JordanReviewsSlugRouteImport.update({
  id: '/Jordan/reviews/$slug',
  path: '/Jordan/reviews/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JordanReviewsIndexInfoRoute = JordanReviewsIndexInfoRouteImport.update({
  id: '/Jordan/reviews/index-info',
  path: '/Jordan/reviews/index-info',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFakeReviewsIndexRoute = AdminFakeReviewsIndexRouteImport.update({
  id: '/fake-reviews/',
  path: '/fake-reviews/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFakeReviewsOrderIdRoute = AdminFakeReviewsOrderIdRouteImport.update({
  id: '/fake-reviews/$orderId',
  path: '/fake-reviews/$orderId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPolicyIndexRoute = AdminPolicyIndexRouteImport.update({
  id: '/policy/',
  path: '/policy/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPolicyOrderIdRoute = AdminPolicyOrderIdRouteImport.update({
  id: '/policy/$orderId',
  path: '/policy/$orderId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPolicyTrainingRoute = AdminPolicyTrainingRouteImport.update({
  id: '/policy/training',
  path: '/policy/training',
  getParentRoute: () => AdminRoute,
} as any)
const AppFakeReviewsIndexRoute = AppFakeReviewsIndexRouteImport.update({
  id: '/fake-reviews/',
  path: '/fake-reviews/',
  getParentRoute: () => AppRoute,
} as any)
const AppFakeReviewsOrderIdRoute = AppFakeReviewsOrderIdRouteImport.update({
  id: '/fake-reviews/$orderId',
  path: '/fake-reviews/$orderId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersOrderIdRoute = AppOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AppRoute,
} as any)
const AppPolicyIndexRoute = AppPolicyIndexRouteImport.update({
  id: '/policy/',
  path: '/policy/',
  getParentRoute: () => AppRoute,
} as any)
const AppPolicyOrderIdRoute = AppPolicyOrderIdRouteImport.update({
  id: '/policy/$orderId',
  path: '/policy/$orderId',
  getParentRoute: () => AppRoute,
} as any)
const UHandleIndexRoute = UHandleIndexRouteImport.update({
  id: '/u/$handle/',
  path: '/u/$handle/',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleSlugRoute = UHandleSlugRouteImport.update({
  id: '/u/$handle/$slug',
  path: '/u/$handle/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDmcaConfirmRoute = ApiPublicDmcaConfirmRouteImport.update({
  id: '/api/public/dmca/confirm',
  path: '/api/public/dmca/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDmcaConfirmSingleRoute =
  ApiPublicDmcaConfirmSingleRouteImport.update({
    id: '/api/public/dmca/confirm-single',
    path: '/api/public/dmca/confirm-single',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDmcaNextBatchRoute = ApiPublicDmcaNextBatchRouteImport.update({
  id: '/api/public/dmca/next-batch',
  path: '/api/public/dmca/next-batch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDmcaNextSingleRoute = ApiPublicDmcaNextSingleRouteImport.update({
  id: '/api/public/dmca/next-single',
  path: '/api/public/dmca/next-single',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDmcaOrdersRoute = ApiPublicDmcaOrdersRouteImport.update({
  id: '/api/public/dmca/orders',
  path: '/api/public/dmca/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDmcaReleaseRoute = ApiPublicDmcaReleaseRouteImport.update({
  id: '/api/public/dmca/release',
  path: '/api/public/dmca/release',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDmcaReleaseSingleRoute =
  ApiPublicDmcaReleaseSingleRouteImport.update({
    id: '/api/public/dmca/release-single',
    path: '/api/public/dmca/release-single',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFakeReviewsCaptureRoute =
  ApiPublicFakeReviewsCaptureRouteImport.update({
    id: '/api/public/fake-reviews/capture',
    path: '/api/public/fake-reviews/capture',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFakeReviewsDripTickRoute =
  ApiPublicFakeReviewsDripTickRouteImport.update({
    id: '/api/public/fake-reviews/drip-tick',
    path: '/api/public/fake-reviews/drip-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFakeReviewsSessionRoute =
  ApiPublicFakeReviewsSessionRouteImport.update({
    id: '/api/public/fake-reviews/session',
    path: '/api/public/fake-reviews/session',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPolicyExtensionConfirmRoute =
  ApiPublicPolicyExtensionConfirmRouteImport.update({
    id: '/api/public/policy-extension/confirm',
    path: '/api/public/policy-extension/confirm',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPolicyExtensionNextRoute =
  ApiPublicPolicyExtensionNextRouteImport.update({
    id: '/api/public/policy-extension/next',
    path: '/api/public/policy-extension/next',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPolicyExtensionOrdersRoute =
  ApiPublicPolicyExtensionOrdersRouteImport.update({
    id: '/api/public/policy-extension/orders',
    path: '/api/public/policy-extension/orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPolicyExtensionReleaseRoute =
  ApiPublicPolicyExtensionReleaseRouteImport.update({
    id: '/api/public/policy-extension/release',
    path: '/api/public/policy-extension/release',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicProfilesNextTargetRoute =
  ApiPublicProfilesNextTargetRouteImport.update({
    id: '/api/public/profiles/next-target',
    path: '/api/public/profiles/next-target',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicProfilesOrdersRoute = ApiPublicProfilesOrdersRouteImport.update({
  id: '/api/public/profiles/orders',
  path: '/api/public/profiles/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProfilesSubmitTargetRoute =
  ApiPublicProfilesSubmitTargetRouteImport.update({
    id: '/api/public/profiles/submit-target',
    path: '/api/public/profiles/submit-target',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicReviewImageSplatRoute =
  ApiPublicReviewImageSplatRouteImport.update({
    id: '/api/public/review-image/$',
    path: '/api/public/review-image/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicUserDmcaConfirmRoute =
  ApiPublicUserDmcaConfirmRouteImport.update({
    id: '/api/public/user-dmca/confirm',
    path: '/api/public/user-dmca/confirm',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicUserDmcaConfirmSingleRoute =
  ApiPublicUserDmcaConfirmSingleRouteImport.update({
    id: '/api/public/user-dmca/confirm-single',
    path: '/api/public/user-dmca/confirm-single',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicUserDmcaNextBatchRoute =
  ApiPublicUserDmcaNextBatchRouteImport.update({
    id: '/api/public/user-dmca/next-batch',
    path: '/api/public/user-dmca/next-batch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicUserDmcaNextSingleRoute =
  ApiPublicUserDmcaNextSingleRouteImport.update({
    id: '/api/public/user-dmca/next-single',
    path: '/api/public/user-dmca/next-single',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicUserDmcaOrdersRoute = ApiPublicUserDmcaOrdersRouteImport.update({
  id: '/api/public/user-dmca/orders',
  path: '/api/public/user-dmca/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUserDmcaReleaseRoute =
  ApiPublicUserDmcaReleaseRouteImport.update({
    id: '/api/public/user-dmca/release',
    path: '/api/public/user-dmca/release',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicUserDmcaReleaseSingleRoute =
  ApiPublicUserDmcaReleaseSingleRouteImport.update({
    id: '/api/public/user-dmca/release-single',
    path: '/api/public/user-dmca/release-single',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/xrpuas-log': typeof XrpuasLogRoute
  '/$profileSlug/$reviewSlug': typeof ProfileSlugReviewSlugRoute
  '/Benedikt-Herrmann/$slug': typeof BenediktHerrmannSlugRoute
  '/Benedikt-Herrmann/index-info': typeof BenediktHerrmannIndexInfoRoute
  '/Jonas-Weber/$slug': typeof JonasWeberSlugRoute
  '/Jonas-Weber/index-info': typeof JonasWeberIndexInfoRoute
  '/admin/afridi': typeof AdminAfridiRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/archive': typeof AdminArchiveRoute
  '/admin/dmca': typeof AdminDmcaRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/robiul': typeof AdminRobiulRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/write': typeof AdminWriteRoute
  '/afridi/$slug': typeof AfridiSlugRoute
  '/afridi/index-info': typeof AfridiIndexInfoRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/app/dmca': typeof AppDmcaRoute
  '/app/guide': typeof AppGuideRoute
  '/app/post': typeof AppPostRoute
  '/app/profiles': typeof AppProfilesRoute
  '/app/settings': typeof AppSettingsRoute
  '/robiul-alam/$slug': typeof RobiulAlamSlugRoute
  '/robiul-alam/index-info': typeof RobiulAlamIndexInfoRoute
  '/$profileSlug/': typeof ProfileSlugIndexRoute
  '/Benedikt-Herrmann/': typeof BenediktHerrmannIndexRoute
  '/Jonas-Weber/': typeof JonasWeberIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/afridi/': typeof AfridiIndexRoute
  '/app/': typeof AppIndexRoute
  '/robiul-alam/': typeof RobiulAlamIndexRoute
  '/Jordan/reviews/$slug': typeof JordanReviewsSlugRoute
  '/Jordan/reviews/index-info': typeof JordanReviewsIndexInfoRoute
  '/admin/fake-reviews/$orderId': typeof AdminFakeReviewsOrderIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/policy/$orderId': typeof AdminPolicyOrderIdRoute
  '/admin/policy/training': typeof AdminPolicyTrainingRoute
  '/app/fake-reviews/$orderId': typeof AppFakeReviewsOrderIdRoute
  '/app/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/app/policy/$orderId': typeof AppPolicyOrderIdRoute
  '/u/$handle/$slug': typeof UHandleSlugRoute
  '/Jordan/reviews/': typeof JordanReviewsIndexRoute
  '/admin/fake-reviews/': typeof AdminFakeReviewsIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/policy/': typeof AdminPolicyIndexRoute
  '/app/fake-reviews/': typeof AppFakeReviewsIndexRoute
  '/app/orders/': typeof AppOrdersIndexRoute
  '/app/policy/': typeof AppPolicyIndexRoute
  '/u/$handle/': typeof UHandleIndexRoute
  '/api/public/dmca/confirm': typeof ApiPublicDmcaConfirmRoute
  '/api/public/dmca/confirm-single': typeof ApiPublicDmcaConfirmSingleRoute
  '/api/public/dmca/next-batch': typeof ApiPublicDmcaNextBatchRoute
  '/api/public/dmca/next-single': typeof ApiPublicDmcaNextSingleRoute
  '/api/public/dmca/orders': typeof ApiPublicDmcaOrdersRoute
  '/api/public/dmca/release': typeof ApiPublicDmcaReleaseRoute
  '/api/public/dmca/release-single': typeof ApiPublicDmcaReleaseSingleRoute
  '/api/public/fake-reviews/capture': typeof ApiPublicFakeReviewsCaptureRoute
  '/api/public/fake-reviews/drip-tick': typeof ApiPublicFakeReviewsDripTickRoute
  '/api/public/fake-reviews/session': typeof ApiPublicFakeReviewsSessionRoute
  '/api/public/policy-extension/confirm': typeof ApiPublicPolicyExtensionConfirmRoute
  '/api/public/policy-extension/next': typeof ApiPublicPolicyExtensionNextRoute
  '/api/public/policy-extension/orders': typeof ApiPublicPolicyExtensionOrdersRoute
  '/api/public/policy-extension/release': typeof ApiPublicPolicyExtensionReleaseRoute
  '/api/public/profiles/next-target': typeof ApiPublicProfilesNextTargetRoute
  '/api/public/profiles/orders': typeof ApiPublicProfilesOrdersRoute
  '/api/public/profiles/submit-target': typeof ApiPublicProfilesSubmitTargetRoute
  '/api/public/review-image/$': typeof ApiPublicReviewImageSplatRoute
  '/api/public/user-dmca/confirm': typeof ApiPublicUserDmcaConfirmRoute
  '/api/public/user-dmca/confirm-single': typeof ApiPublicUserDmcaConfirmSingleRoute
  '/api/public/user-dmca/next-batch': typeof ApiPublicUserDmcaNextBatchRoute
  '/api/public/user-dmca/next-single': typeof ApiPublicUserDmcaNextSingleRoute
  '/api/public/user-dmca/orders': typeof ApiPublicUserDmcaOrdersRoute
  '/api/public/user-dmca/release': typeof ApiPublicUserDmcaReleaseRoute
  '/api/public/user-dmca/release-single': typeof ApiPublicUserDmcaReleaseSingleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/xrpuas-log': typeof XrpuasLogRoute
  '/$profileSlug/$reviewSlug': typeof ProfileSlugReviewSlugRoute
  '/Benedikt-Herrmann/$slug': typeof BenediktHerrmannSlugRoute
  '/Benedikt-Herrmann/index-info': typeof BenediktHerrmannIndexInfoRoute
  '/Jonas-Weber/$slug': typeof JonasWeberSlugRoute
  '/Jonas-Weber/index-info': typeof JonasWeberIndexInfoRoute
  '/admin/afridi': typeof AdminAfridiRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/archive': typeof AdminArchiveRoute
  '/admin/dmca': typeof AdminDmcaRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/robiul': typeof AdminRobiulRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/write': typeof AdminWriteRoute
  '/afridi/$slug': typeof AfridiSlugRoute
  '/afridi/index-info': typeof AfridiIndexInfoRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/app/dmca': typeof AppDmcaRoute
  '/app/guide': typeof AppGuideRoute
  '/app/post': typeof AppPostRoute
  '/app/profiles': typeof AppProfilesRoute
  '/app/settings': typeof AppSettingsRoute
  '/robiul-alam/$slug': typeof RobiulAlamSlugRoute
  '/robiul-alam/index-info': typeof RobiulAlamIndexInfoRoute
  '/$profileSlug': typeof ProfileSlugIndexRoute
  '/Benedikt-Herrmann': typeof BenediktHerrmannIndexRoute
  '/Jonas-Weber': typeof JonasWeberIndexRoute
  '/admin': typeof AdminIndexRoute
  '/afridi': typeof AfridiIndexRoute
  '/app': typeof AppIndexRoute
  '/robiul-alam': typeof RobiulAlamIndexRoute
  '/Jordan/reviews/$slug': typeof JordanReviewsSlugRoute
  '/Jordan/reviews/index-info': typeof JordanReviewsIndexInfoRoute
  '/admin/fake-reviews/$orderId': typeof AdminFakeReviewsOrderIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/policy/$orderId': typeof AdminPolicyOrderIdRoute
  '/admin/policy/training': typeof AdminPolicyTrainingRoute
  '/app/fake-reviews/$orderId': typeof AppFakeReviewsOrderIdRoute
  '/app/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/app/policy/$orderId': typeof AppPolicyOrderIdRoute
  '/u/$handle/$slug': typeof UHandleSlugRoute
  '/Jordan/reviews': typeof JordanReviewsIndexRoute
  '/admin/fake-reviews': typeof AdminFakeReviewsIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/policy': typeof AdminPolicyIndexRoute
  '/app/fake-reviews': typeof AppFakeReviewsIndexRoute
  '/app/orders': typeof AppOrdersIndexRoute
  '/app/policy': typeof AppPolicyIndexRoute
  '/u/$handle': typeof UHandleIndexRoute
  '/api/public/dmca/confirm': typeof ApiPublicDmcaConfirmRoute
  '/api/public/dmca/confirm-single': typeof ApiPublicDmcaConfirmSingleRoute
  '/api/public/dmca/next-batch': typeof ApiPublicDmcaNextBatchRoute
  '/api/public/dmca/next-single': typeof ApiPublicDmcaNextSingleRoute
  '/api/public/dmca/orders': typeof ApiPublicDmcaOrdersRoute
  '/api/public/dmca/release': typeof ApiPublicDmcaReleaseRoute
  '/api/public/dmca/release-single': typeof ApiPublicDmcaReleaseSingleRoute
  '/api/public/fake-reviews/capture': typeof ApiPublicFakeReviewsCaptureRoute
  '/api/public/fake-reviews/drip-tick': typeof ApiPublicFakeReviewsDripTickRoute
  '/api/public/fake-reviews/session': typeof ApiPublicFakeReviewsSessionRoute
  '/api/public/policy-extension/confirm': typeof ApiPublicPolicyExtensionConfirmRoute
  '/api/public/policy-extension/next': typeof ApiPublicPolicyExtensionNextRoute
  '/api/public/policy-extension/orders': typeof ApiPublicPolicyExtensionOrdersRoute
  '/api/public/policy-extension/release': typeof ApiPublicPolicyExtensionReleaseRoute
  '/api/public/profiles/next-target': typeof ApiPublicProfilesNextTargetRoute
  '/api/public/profiles/orders': typeof ApiPublicProfilesOrdersRoute
  '/api/public/profiles/submit-target': typeof ApiPublicProfilesSubmitTargetRoute
  '/api/public/review-image/$': typeof ApiPublicReviewImageSplatRoute
  '/api/public/user-dmca/confirm': typeof ApiPublicUserDmcaConfirmRoute
  '/api/public/user-dmca/confirm-single': typeof ApiPublicUserDmcaConfirmSingleRoute
  '/api/public/user-dmca/next-batch': typeof ApiPublicUserDmcaNextBatchRoute
  '/api/public/user-dmca/next-single': typeof ApiPublicUserDmcaNextSingleRoute
  '/api/public/user-dmca/orders': typeof ApiPublicUserDmcaOrdersRoute
  '/api/public/user-dmca/release': typeof ApiPublicUserDmcaReleaseRoute
  '/api/public/user-dmca/release-single': typeof ApiPublicUserDmcaReleaseSingleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/xrpuas-log': typeof XrpuasLogRoute
  '/$profileSlug/$reviewSlug': typeof ProfileSlugReviewSlugRoute
  '/Benedikt-Herrmann/$slug': typeof BenediktHerrmannSlugRoute
  '/Benedikt-Herrmann/index-info': typeof BenediktHerrmannIndexInfoRoute
  '/Jonas-Weber/$slug': typeof JonasWeberSlugRoute
  '/Jonas-Weber/index-info': typeof JonasWeberIndexInfoRoute
  '/admin/afridi': typeof AdminAfridiRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/archive': typeof AdminArchiveRoute
  '/admin/dmca': typeof AdminDmcaRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/robiul': typeof AdminRobiulRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/write': typeof AdminWriteRoute
  '/afridi/$slug': typeof AfridiSlugRoute
  '/afridi/index-info': typeof AfridiIndexInfoRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/app/dmca': typeof AppDmcaRoute
  '/app/guide': typeof AppGuideRoute
  '/app/post': typeof AppPostRoute
  '/app/profiles': typeof AppProfilesRoute
  '/app/settings': typeof AppSettingsRoute
  '/robiul-alam/$slug': typeof RobiulAlamSlugRoute
  '/robiul-alam/index-info': typeof RobiulAlamIndexInfoRoute
  '/$profileSlug/': typeof ProfileSlugIndexRoute
  '/Benedikt-Herrmann/': typeof BenediktHerrmannIndexRoute
  '/Jonas-Weber/': typeof JonasWeberIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/afridi/': typeof AfridiIndexRoute
  '/app/': typeof AppIndexRoute
  '/robiul-alam/': typeof RobiulAlamIndexRoute
  '/Jordan/reviews/$slug': typeof JordanReviewsSlugRoute
  '/Jordan/reviews/index-info': typeof JordanReviewsIndexInfoRoute
  '/admin/fake-reviews/$orderId': typeof AdminFakeReviewsOrderIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/policy/$orderId': typeof AdminPolicyOrderIdRoute
  '/admin/policy/training': typeof AdminPolicyTrainingRoute
  '/app/fake-reviews/$orderId': typeof AppFakeReviewsOrderIdRoute
  '/app/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/app/policy/$orderId': typeof AppPolicyOrderIdRoute
  '/u/$handle/$slug': typeof UHandleSlugRoute
  '/Jordan/reviews/': typeof JordanReviewsIndexRoute
  '/admin/fake-reviews/': typeof AdminFakeReviewsIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/policy/': typeof AdminPolicyIndexRoute
  '/app/fake-reviews/': typeof AppFakeReviewsIndexRoute
  '/app/orders/': typeof AppOrdersIndexRoute
  '/app/policy/': typeof AppPolicyIndexRoute
  '/u/$handle/': typeof UHandleIndexRoute
  '/api/public/dmca/confirm': typeof ApiPublicDmcaConfirmRoute
  '/api/public/dmca/confirm-single': typeof ApiPublicDmcaConfirmSingleRoute
  '/api/public/dmca/next-batch': typeof ApiPublicDmcaNextBatchRoute
  '/api/public/dmca/next-single': typeof ApiPublicDmcaNextSingleRoute
  '/api/public/dmca/orders': typeof ApiPublicDmcaOrdersRoute
  '/api/public/dmca/release': typeof ApiPublicDmcaReleaseRoute
  '/api/public/dmca/release-single': typeof ApiPublicDmcaReleaseSingleRoute
  '/api/public/fake-reviews/capture': typeof ApiPublicFakeReviewsCaptureRoute
  '/api/public/fake-reviews/drip-tick': typeof ApiPublicFakeReviewsDripTickRoute
  '/api/public/fake-reviews/session': typeof ApiPublicFakeReviewsSessionRoute
  '/api/public/policy-extension/confirm': typeof ApiPublicPolicyExtensionConfirmRoute
  '/api/public/policy-extension/next': typeof ApiPublicPolicyExtensionNextRoute
  '/api/public/policy-extension/orders': typeof ApiPublicPolicyExtensionOrdersRoute
  '/api/public/policy-extension/release': typeof ApiPublicPolicyExtensionReleaseRoute
  '/api/public/profiles/next-target': typeof ApiPublicProfilesNextTargetRoute
  '/api/public/profiles/orders': typeof ApiPublicProfilesOrdersRoute
  '/api/public/profiles/submit-target': typeof ApiPublicProfilesSubmitTargetRoute
  '/api/public/review-image/$': typeof ApiPublicReviewImageSplatRoute
  '/api/public/user-dmca/confirm': typeof ApiPublicUserDmcaConfirmRoute
  '/api/public/user-dmca/confirm-single': typeof ApiPublicUserDmcaConfirmSingleRoute
  '/api/public/user-dmca/next-batch': typeof ApiPublicUserDmcaNextBatchRoute
  '/api/public/user-dmca/next-single': typeof ApiPublicUserDmcaNextSingleRoute
  '/api/public/user-dmca/orders': typeof ApiPublicUserDmcaOrdersRoute
  '/api/public/user-dmca/release': typeof ApiPublicUserDmcaReleaseRoute
  '/api/public/user-dmca/release-single': typeof ApiPublicUserDmcaReleaseSingleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/sitemap.xml'
    | '/xrpuas-log'
    | '/$profileSlug/$reviewSlug'
    | '/Benedikt-Herrmann/$slug'
    | '/Benedikt-Herrmann/index-info'
    | '/Jonas-Weber/$slug'
    | '/Jonas-Weber/index-info'
    | '/admin/afridi'
    | '/admin/ai'
    | '/admin/archive'
    | '/admin/dmca'
    | '/admin/import'
    | '/admin/robiul'
    | '/admin/users'
    | '/admin/write'
    | '/afridi/$slug'
    | '/afridi/index-info'
    | '/api/ai-chat'
    | '/app/dmca'
    | '/app/guide'
    | '/app/post'
    | '/app/profiles'
    | '/app/settings'
    | '/robiul-alam/$slug'
    | '/robiul-alam/index-info'
    | '/$profileSlug/'
    | '/Benedikt-Herrmann/'
    | '/Jonas-Weber/'
    | '/admin/'
    | '/afridi/'
    | '/app/'
    | '/robiul-alam/'
    | '/Jordan/reviews/$slug'
    | '/Jordan/reviews/index-info'
    | '/admin/fake-reviews/$orderId'
    | '/admin/orders/$orderId'
    | '/admin/policy/$orderId'
    | '/admin/policy/training'
    | '/app/fake-reviews/$orderId'
    | '/app/orders/$orderId'
    | '/app/policy/$orderId'
    | '/u/$handle/$slug'
    | '/Jordan/reviews/'
    | '/admin/fake-reviews/'
    | '/admin/orders/'
    | '/admin/policy/'
    | '/app/fake-reviews/'
    | '/app/orders/'
    | '/app/policy/'
    | '/u/$handle/'
    | '/api/public/dmca/confirm'
    | '/api/public/dmca/confirm-single'
    | '/api/public/dmca/next-batch'
    | '/api/public/dmca/next-single'
    | '/api/public/dmca/orders'
    | '/api/public/dmca/release'
    | '/api/public/dmca/release-single'
    | '/api/public/fake-reviews/capture'
    | '/api/public/fake-reviews/drip-tick'
    | '/api/public/fake-reviews/session'
    | '/api/public/policy-extension/confirm'
    | '/api/public/policy-extension/next'
    | '/api/public/policy-extension/orders'
    | '/api/public/policy-extension/release'
    | '/api/public/profiles/next-target'
    | '/api/public/profiles/orders'
    | '/api/public/profiles/submit-target'
    | '/api/public/review-image/$'
    | '/api/public/user-dmca/confirm'
    | '/api/public/user-dmca/confirm-single'
    | '/api/public/user-dmca/next-batch'
    | '/api/public/user-dmca/next-single'
    | '/api/public/user-dmca/orders'
    | '/api/public/user-dmca/release'
    | '/api/public/user-dmca/release-single'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/xrpuas-log'
    | '/$profileSlug/$reviewSlug'
    | '/Benedikt-Herrmann/$slug'
    | '/Benedikt-Herrmann/index-info'
    | '/Jonas-Weber/$slug'
    | '/Jonas-Weber/index-info'
    | '/admin/afridi'
    | '/admin/ai'
    | '/admin/archive'
    | '/admin/dmca'
    | '/admin/import'
    | '/admin/robiul'
    | '/admin/users'
    | '/admin/write'
    | '/afridi/$slug'
    | '/afridi/index-info'
    | '/api/ai-chat'
    | '/app/dmca'
    | '/app/guide'
    | '/app/post'
    | '/app/profiles'
    | '/app/settings'
    | '/robiul-alam/$slug'
    | '/robiul-alam/index-info'
    | '/$profileSlug'
    | '/Benedikt-Herrmann'
    | '/Jonas-Weber'
    | '/admin'
    | '/afridi'
    | '/app'
    | '/robiul-alam'
    | '/Jordan/reviews/$slug'
    | '/Jordan/reviews/index-info'
    | '/admin/fake-reviews/$orderId'
    | '/admin/orders/$orderId'
    | '/admin/policy/$orderId'
    | '/admin/policy/training'
    | '/app/fake-reviews/$orderId'
    | '/app/orders/$orderId'
    | '/app/policy/$orderId'
    | '/u/$handle/$slug'
    | '/Jordan/reviews'
    | '/admin/fake-reviews'
    | '/admin/orders'
    | '/admin/policy'
    | '/app/fake-reviews'
    | '/app/orders'
    | '/app/policy'
    | '/u/$handle'
    | '/api/public/dmca/confirm'
    | '/api/public/dmca/confirm-single'
    | '/api/public/dmca/next-batch'
    | '/api/public/dmca/next-single'
    | '/api/public/dmca/orders'
    | '/api/public/dmca/release'
    | '/api/public/dmca/release-single'
    | '/api/public/fake-reviews/capture'
    | '/api/public/fake-reviews/drip-tick'
    | '/api/public/fake-reviews/session'
    | '/api/public/policy-extension/confirm'
    | '/api/public/policy-extension/next'
    | '/api/public/policy-extension/orders'
    | '/api/public/policy-extension/release'
    | '/api/public/profiles/next-target'
    | '/api/public/profiles/orders'
    | '/api/public/profiles/submit-target'
    | '/api/public/review-image/$'
    | '/api/public/user-dmca/confirm'
    | '/api/public/user-dmca/confirm-single'
    | '/api/public/user-dmca/next-batch'
    | '/api/public/user-dmca/next-single'
    | '/api/public/user-dmca/orders'
    | '/api/public/user-dmca/release'
    | '/api/public/user-dmca/release-single'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/sitemap.xml'
    | '/xrpuas-log'
    | '/$profileSlug/$reviewSlug'
    | '/Benedikt-Herrmann/$slug'
    | '/Benedikt-Herrmann/index-info'
    | '/Jonas-Weber/$slug'
    | '/Jonas-Weber/index-info'
    | '/admin/afridi'
    | '/admin/ai'
    | '/admin/archive'
    | '/admin/dmca'
    | '/admin/import'
    | '/admin/robiul'
    | '/admin/users'
    | '/admin/write'
    | '/afridi/$slug'
    | '/afridi/index-info'
    | '/api/ai-chat'
    | '/app/dmca'
    | '/app/guide'
    | '/app/post'
    | '/app/profiles'
    | '/app/settings'
    | '/robiul-alam/$slug'
    | '/robiul-alam/index-info'
    | '/$profileSlug/'
    | '/Benedikt-Herrmann/'
    | '/Jonas-Weber/'
    | '/admin/'
    | '/afridi/'
    | '/app/'
    | '/robiul-alam/'
    | '/Jordan/reviews/$slug'
    | '/Jordan/reviews/index-info'
    | '/admin/fake-reviews/$orderId'
    | '/admin/orders/$orderId'
    | '/admin/policy/$orderId'
    | '/admin/policy/training'
    | '/app/fake-reviews/$orderId'
    | '/app/orders/$orderId'
    | '/app/policy/$orderId'
    | '/u/$handle/$slug'
    | '/Jordan/reviews/'
    | '/admin/fake-reviews/'
    | '/admin/orders/'
    | '/admin/policy/'
    | '/app/fake-reviews/'
    | '/app/orders/'
    | '/app/policy/'
    | '/u/$handle/'
    | '/api/public/dmca/confirm'
    | '/api/public/dmca/confirm-single'
    | '/api/public/dmca/next-batch'
    | '/api/public/dmca/next-single'
    | '/api/public/dmca/orders'
    | '/api/public/dmca/release'
    | '/api/public/dmca/release-single'
    | '/api/public/fake-reviews/capture'
    | '/api/public/fake-reviews/drip-tick'
    | '/api/public/fake-reviews/session'
    | '/api/public/policy-extension/confirm'
    | '/api/public/policy-extension/next'
    | '/api/public/policy-extension/orders'
    | '/api/public/policy-extension/release'
    | '/api/public/profiles/next-target'
    | '/api/public/profiles/orders'
    | '/api/public/profiles/submit-target'
    | '/api/public/review-image/$'
    | '/api/public/user-dmca/confirm'
    | '/api/public/user-dmca/confirm-single'
    | '/api/public/user-dmca/next-batch'
    | '/api/public/user-dmca/next-single'
    | '/api/public/user-dmca/orders'
    | '/api/public/user-dmca/release'
    | '/api/public/user-dmca/release-single'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  XrpuasLogRoute: typeof XrpuasLogRoute
  ProfileSlugReviewSlugRoute: typeof ProfileSlugReviewSlugRoute
  BenediktHerrmannSlugRoute: typeof BenediktHerrmannSlugRoute
  BenediktHerrmannIndexInfoRoute: typeof BenediktHerrmannIndexInfoRoute
  JonasWeberSlugRoute: typeof JonasWeberSlugRoute
  JonasWeberIndexInfoRoute: typeof JonasWeberIndexInfoRoute
  AfridiSlugRoute: typeof AfridiSlugRoute
  AfridiIndexInfoRoute: typeof AfridiIndexInfoRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  RobiulAlamSlugRoute: typeof RobiulAlamSlugRoute
  RobiulAlamIndexInfoRoute: typeof RobiulAlamIndexInfoRoute
  ProfileSlugIndexRoute: typeof ProfileSlugIndexRoute
  BenediktHerrmannIndexRoute: typeof BenediktHerrmannIndexRoute
  JonasWeberIndexRoute: typeof JonasWeberIndexRoute
  AfridiIndexRoute: typeof AfridiIndexRoute
  RobiulAlamIndexRoute: typeof RobiulAlamIndexRoute
  JordanReviewsSlugRoute: typeof JordanReviewsSlugRoute
  JordanReviewsIndexInfoRoute: typeof JordanReviewsIndexInfoRoute
  UHandleSlugRoute: typeof UHandleSlugRoute
  JordanReviewsIndexRoute: typeof JordanReviewsIndexRoute
  UHandleIndexRoute: typeof UHandleIndexRoute
  ApiPublicDmcaConfirmRoute: typeof ApiPublicDmcaConfirmRoute
  ApiPublicDmcaConfirmSingleRoute: typeof ApiPublicDmcaConfirmSingleRoute
  ApiPublicDmcaNextBatchRoute: typeof ApiPublicDmcaNextBatchRoute
  ApiPublicDmcaNextSingleRoute: typeof ApiPublicDmcaNextSingleRoute
  ApiPublicDmcaOrdersRoute: typeof ApiPublicDmcaOrdersRoute
  ApiPublicDmcaReleaseRoute: typeof ApiPublicDmcaReleaseRoute
  ApiPublicDmcaReleaseSingleRoute: typeof ApiPublicDmcaReleaseSingleRoute
  ApiPublicFakeReviewsCaptureRoute: typeof ApiPublicFakeReviewsCaptureRoute
  ApiPublicFakeReviewsDripTickRoute: typeof ApiPublicFakeReviewsDripTickRoute
  ApiPublicFakeReviewsSessionRoute: typeof ApiPublicFakeReviewsSessionRoute
  ApiPublicPolicyExtensionConfirmRoute: typeof ApiPublicPolicyExtensionConfirmRoute
  ApiPublicPolicyExtensionNextRoute: typeof ApiPublicPolicyExtensionNextRoute
  ApiPublicPolicyExtensionOrdersRoute: typeof ApiPublicPolicyExtensionOrdersRoute
  ApiPublicPolicyExtensionReleaseRoute: typeof ApiPublicPolicyExtensionReleaseRoute
  ApiPublicProfilesNextTargetRoute: typeof ApiPublicProfilesNextTargetRoute
  ApiPublicProfilesOrdersRoute: typeof ApiPublicProfilesOrdersRoute
  ApiPublicProfilesSubmitTargetRoute: typeof ApiPublicProfilesSubmitTargetRoute
  ApiPublicReviewImageSplatRoute: typeof ApiPublicReviewImageSplatRoute
  ApiPublicUserDmcaConfirmRoute: typeof ApiPublicUserDmcaConfirmRoute
  ApiPublicUserDmcaConfirmSingleRoute: typeof ApiPublicUserDmcaConfirmSingleRoute
  ApiPublicUserDmcaNextBatchRoute: typeof ApiPublicUserDmcaNextBatchRoute
  ApiPublicUserDmcaNextSingleRoute: typeof ApiPublicUserDmcaNextSingleRoute
  ApiPublicUserDmcaOrdersRoute: typeof ApiPublicUserDmcaOrdersRoute
  ApiPublicUserDmcaReleaseRoute: typeof ApiPublicUserDmcaReleaseRoute
  ApiPublicUserDmcaReleaseSingleRoute: typeof ApiPublicUserDmcaReleaseSingleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xrpuas-log': {
      id: '/xrpuas-log'
      path: '/xrpuas-log'
      fullPath: '/xrpuas-log'
      preLoaderRoute: typeof XrpuasLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$profileSlug/': {
      id: '/$profileSlug/'
      path: '/$profileSlug'
      fullPath: '/$profileSlug/'
      preLoaderRoute: typeof ProfileSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$profileSlug/$reviewSlug': {
      id: '/$profileSlug/$reviewSlug'
      path: '/$profileSlug/$reviewSlug'
      fullPath: '/$profileSlug/$reviewSlug'
      preLoaderRoute: typeof ProfileSlugReviewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Benedikt-Herrmann/': {
      id: '/Benedikt-Herrmann/'
      path: '/Benedikt-Herrmann'
      fullPath: '/Benedikt-Herrmann/'
      preLoaderRoute: typeof BenediktHerrmannIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Benedikt-Herrmann/$slug': {
      id: '/Benedikt-Herrmann/$slug'
      path: '/Benedikt-Herrmann/$slug'
      fullPath: '/Benedikt-Herrmann/$slug'
      preLoaderRoute: typeof BenediktHerrmannSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Benedikt-Herrmann/index-info': {
      id: '/Benedikt-Herrmann/index-info'
      path: '/Benedikt-Herrmann/index-info'
      fullPath: '/Benedikt-Herrmann/index-info'
      preLoaderRoute: typeof BenediktHerrmannIndexInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Jonas-Weber/': {
      id: '/Jonas-Weber/'
      path: '/Jonas-Weber'
      fullPath: '/Jonas-Weber/'
      preLoaderRoute: typeof JonasWeberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Jonas-Weber/$slug': {
      id: '/Jonas-Weber/$slug'
      path: '/Jonas-Weber/$slug'
      fullPath: '/Jonas-Weber/$slug'
      preLoaderRoute: typeof JonasWeberSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Jonas-Weber/index-info': {
      id: '/Jonas-Weber/index-info'
      path: '/Jonas-Weber/index-info'
      fullPath: '/Jonas-Weber/index-info'
      preLoaderRoute: typeof JonasWeberIndexInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/afridi': {
      id: '/admin/afridi'
      path: '/afridi'
      fullPath: '/admin/afridi'
      preLoaderRoute: typeof AdminAfridiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/archive': {
      id: '/admin/archive'
      path: '/archive'
      fullPath: '/admin/archive'
      preLoaderRoute: typeof AdminArchiveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dmca': {
      id: '/admin/dmca'
      path: '/dmca'
      fullPath: '/admin/dmca'
      preLoaderRoute: typeof AdminDmcaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/robiul': {
      id: '/admin/robiul'
      path: '/robiul'
      fullPath: '/admin/robiul'
      preLoaderRoute: typeof AdminRobiulRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/write': {
      id: '/admin/write'
      path: '/write'
      fullPath: '/admin/write'
      preLoaderRoute: typeof AdminWriteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/afridi/': {
      id: '/afridi/'
      path: '/afridi'
      fullPath: '/afridi/'
      preLoaderRoute: typeof AfridiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afridi/$slug': {
      id: '/afridi/$slug'
      path: '/afridi/$slug'
      fullPath: '/afridi/$slug'
      preLoaderRoute: typeof AfridiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afridi/index-info': {
      id: '/afridi/index-info'
      path: '/afridi/index-info'
      fullPath: '/afridi/index-info'
      preLoaderRoute: typeof AfridiIndexInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-chat': {
      id: '/api/ai-chat'
      path: '/api/ai-chat'
      fullPath: '/api/ai-chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dmca': {
      id: '/app/dmca'
      path: '/dmca'
      fullPath: '/app/dmca'
      preLoaderRoute: typeof AppDmcaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/guide': {
      id: '/app/guide'
      path: '/guide'
      fullPath: '/app/guide'
      preLoaderRoute: typeof AppGuideRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/post': {
      id: '/app/post'
      path: '/post'
      fullPath: '/app/post'
      preLoaderRoute: typeof AppPostRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profiles': {
      id: '/app/profiles'
      path: '/profiles'
      fullPath: '/app/profiles'
      preLoaderRoute: typeof AppProfilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/robiul-alam/': {
      id: '/robiul-alam/'
      path: '/robiul-alam'
      fullPath: '/robiul-alam/'
      preLoaderRoute: typeof RobiulAlamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robiul-alam/$slug': {
      id: '/robiul-alam/$slug'
      path: '/robiul-alam/$slug'
      fullPath: '/robiul-alam/$slug'
      preLoaderRoute: typeof RobiulAlamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robiul-alam/index-info': {
      id: '/robiul-alam/index-info'
      path: '/robiul-alam/index-info'
      fullPath: '/robiul-alam/index-info'
      preLoaderRoute: typeof RobiulAlamIndexInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Jordan/reviews/': {
      id: '/Jordan/reviews/'
      path: '/Jordan/reviews'
      fullPath: '/Jordan/reviews/'
      preLoaderRoute: typeof JordanReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Jordan/reviews/$slug': {
      id: '/Jordan/reviews/$slug'
      path: '/Jordan/reviews/$slug'
      fullPath: '/Jordan/reviews/$slug'
      preLoaderRoute: typeof JordanReviewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Jordan/reviews/index-info': {
      id: '/Jordan/reviews/index-info'
      path: '/Jordan/reviews/index-info'
      fullPath: '/Jordan/reviews/index-info'
      preLoaderRoute: typeof JordanReviewsIndexInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fake-reviews/': {
      id: '/admin/fake-reviews/'
      path: '/fake-reviews'
      fullPath: '/admin/fake-reviews/'
      preLoaderRoute: typeof AdminFakeReviewsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fake-reviews/$orderId': {
      id: '/admin/fake-reviews/$orderId'
      path: '/fake-reviews/$orderId'
      fullPath: '/admin/fake-reviews/$orderId'
      preLoaderRoute: typeof AdminFakeReviewsOrderIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/policy/': {
      id: '/admin/policy/'
      path: '/policy'
      fullPath: '/admin/policy/'
      preLoaderRoute: typeof AdminPolicyIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/policy/$orderId': {
      id: '/admin/policy/$orderId'
      path: '/policy/$orderId'
      fullPath: '/admin/policy/$orderId'
      preLoaderRoute: typeof AdminPolicyOrderIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/policy/training': {
      id: '/admin/policy/training'
      path: '/policy/training'
      fullPath: '/admin/policy/training'
      preLoaderRoute: typeof AdminPolicyTrainingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/fake-reviews/': {
      id: '/app/fake-reviews/'
      path: '/fake-reviews'
      fullPath: '/app/fake-reviews/'
      preLoaderRoute: typeof AppFakeReviewsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fake-reviews/$orderId': {
      id: '/app/fake-reviews/$orderId'
      path: '/fake-reviews/$orderId'
      fullPath: '/app/fake-reviews/$orderId'
      preLoaderRoute: typeof AppFakeReviewsOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders/': {
      id: '/app/orders/'
      path: '/orders'
      fullPath: '/app/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders/$orderId': {
      id: '/app/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/app/orders/$orderId'
      preLoaderRoute: typeof AppOrdersOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/policy/': {
      id: '/app/policy/'
      path: '/policy'
      fullPath: '/app/policy/'
      preLoaderRoute: typeof AppPolicyIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/policy/$orderId': {
      id: '/app/policy/$orderId'
      path: '/policy/$orderId'
      fullPath: '/app/policy/$orderId'
      preLoaderRoute: typeof AppPolicyOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/u/$handle/': {
      id: '/u/$handle/'
      path: '/u/$handle'
      fullPath: '/u/$handle/'
      preLoaderRoute: typeof UHandleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle/$slug': {
      id: '/u/$handle/$slug'
      path: '/u/$handle/$slug'
      fullPath: '/u/$handle/$slug'
      preLoaderRoute: typeof UHandleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dmca/confirm': {
      id: '/api/public/dmca/confirm'
      path: '/api/public/dmca/confirm'
      fullPath: '/api/public/dmca/confirm'
      preLoaderRoute: typeof ApiPublicDmcaConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dmca/confirm-single': {
      id: '/api/public/dmca/confirm-single'
      path: '/api/public/dmca/confirm-single'
      fullPath: '/api/public/dmca/confirm-single'
      preLoaderRoute: typeof ApiPublicDmcaConfirmSingleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dmca/next-batch': {
      id: '/api/public/dmca/next-batch'
      path: '/api/public/dmca/next-batch'
      fullPath: '/api/public/dmca/next-batch'
      preLoaderRoute: typeof ApiPublicDmcaNextBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dmca/next-single': {
      id: '/api/public/dmca/next-single'
      path: '/api/public/dmca/next-single'
      fullPath: '/api/public/dmca/next-single'
      preLoaderRoute: typeof ApiPublicDmcaNextSingleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dmca/orders': {
      id: '/api/public/dmca/orders'
      path: '/api/public/dmca/orders'
      fullPath: '/api/public/dmca/orders'
      preLoaderRoute: typeof ApiPublicDmcaOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dmca/release': {
      id: '/api/public/dmca/release'
      path: '/api/public/dmca/release'
      fullPath: '/api/public/dmca/release'
      preLoaderRoute: typeof ApiPublicDmcaReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dmca/release-single': {
      id: '/api/public/dmca/release-single'
      path: '/api/public/dmca/release-single'
      fullPath: '/api/public/dmca/release-single'
      preLoaderRoute: typeof ApiPublicDmcaReleaseSingleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fake-reviews/capture': {
      id: '/api/public/fake-reviews/capture'
      path: '/api/public/fake-reviews/capture'
      fullPath: '/api/public/fake-reviews/capture'
      preLoaderRoute: typeof ApiPublicFakeReviewsCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fake-reviews/drip-tick': {
      id: '/api/public/fake-reviews/drip-tick'
      path: '/api/public/fake-reviews/drip-tick'
      fullPath: '/api/public/fake-reviews/drip-tick'
      preLoaderRoute: typeof ApiPublicFakeReviewsDripTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fake-reviews/session': {
      id: '/api/public/fake-reviews/session'
      path: '/api/public/fake-reviews/session'
      fullPath: '/api/public/fake-reviews/session'
      preLoaderRoute: typeof ApiPublicFakeReviewsSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/policy-extension/confirm': {
      id: '/api/public/policy-extension/confirm'
      path: '/api/public/policy-extension/confirm'
      fullPath: '/api/public/policy-extension/confirm'
      preLoaderRoute: typeof ApiPublicPolicyExtensionConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/policy-extension/next': {
      id: '/api/public/policy-extension/next'
      path: '/api/public/policy-extension/next'
      fullPath: '/api/public/policy-extension/next'
      preLoaderRoute: typeof ApiPublicPolicyExtensionNextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/policy-extension/orders': {
      id: '/api/public/policy-extension/orders'
      path: '/api/public/policy-extension/orders'
      fullPath: '/api/public/policy-extension/orders'
      preLoaderRoute: typeof ApiPublicPolicyExtensionOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/policy-extension/release': {
      id: '/api/public/policy-extension/release'
      path: '/api/public/policy-extension/release'
      fullPath: '/api/public/policy-extension/release'
      preLoaderRoute: typeof ApiPublicPolicyExtensionReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/profiles/next-target': {
      id: '/api/public/profiles/next-target'
      path: '/api/public/profiles/next-target'
      fullPath: '/api/public/profiles/next-target'
      preLoaderRoute: typeof ApiPublicProfilesNextTargetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/profiles/orders': {
      id: '/api/public/profiles/orders'
      path: '/api/public/profiles/orders'
      fullPath: '/api/public/profiles/orders'
      preLoaderRoute: typeof ApiPublicProfilesOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/profiles/submit-target': {
      id: '/api/public/profiles/submit-target'
      path: '/api/public/profiles/submit-target'
      fullPath: '/api/public/profiles/submit-target'
      preLoaderRoute: typeof ApiPublicProfilesSubmitTargetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/review-image/$': {
      id: '/api/public/review-image/$'
      path: '/api/public/review-image/$'
      fullPath: '/api/public/review-image/$'
      preLoaderRoute: typeof ApiPublicReviewImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/user-dmca/confirm': {
      id: '/api/public/user-dmca/confirm'
      path: '/api/public/user-dmca/confirm'
      fullPath: '/api/public/user-dmca/confirm'
      preLoaderRoute: typeof ApiPublicUserDmcaConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/user-dmca/confirm-single': {
      id: '/api/public/user-dmca/confirm-single'
      path: '/api/public/user-dmca/confirm-single'
      fullPath: '/api/public/user-dmca/confirm-single'
      preLoaderRoute: typeof ApiPublicUserDmcaConfirmSingleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/user-dmca/next-batch': {
      id: '/api/public/user-dmca/next-batch'
      path: '/api/public/user-dmca/next-batch'
      fullPath: '/api/public/user-dmca/next-batch'
      preLoaderRoute: typeof ApiPublicUserDmcaNextBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/user-dmca/next-single': {
      id: '/api/public/user-dmca/next-single'
      path: '/api/public/user-dmca/next-single'
      fullPath: '/api/public/user-dmca/next-single'
      preLoaderRoute: typeof ApiPublicUserDmcaNextSingleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/user-dmca/orders': {
      id: '/api/public/user-dmca/orders'
      path: '/api/public/user-dmca/orders'
      fullPath: '/api/public/user-dmca/orders'
      preLoaderRoute: typeof ApiPublicUserDmcaOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/user-dmca/release': {
      id: '/api/public/user-dmca/release'
      path: '/api/public/user-dmca/release'
      fullPath: '/api/public/user-dmca/release'
      preLoaderRoute: typeof ApiPublicUserDmcaReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/user-dmca/release-single': {
      id: '/api/public/user-dmca/release-single'
      path: '/api/public/user-dmca/release-single'
      fullPath: '/api/public/user-dmca/release-single'
      preLoaderRoute: typeof ApiPublicUserDmcaReleaseSingleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAfridiRoute: typeof AdminAfridiRoute
  AdminAiRoute: typeof AdminAiRoute
  AdminArchiveRoute: typeof AdminArchiveRoute
  AdminDmcaRoute: typeof AdminDmcaRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminRobiulRoute: typeof AdminRobiulRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWriteRoute: typeof AdminWriteRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminFakeReviewsOrderIdRoute: typeof AdminFakeReviewsOrderIdRoute
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
  AdminPolicyOrderIdRoute: typeof AdminPolicyOrderIdRoute
  AdminPolicyTrainingRoute: typeof AdminPolicyTrainingRoute
  AdminFakeReviewsIndexRoute: typeof AdminFakeReviewsIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminPolicyIndexRoute: typeof AdminPolicyIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAfridiRoute: AdminAfridiRoute,
  AdminAiRoute: AdminAiRoute,
  AdminArchiveRoute: AdminArchiveRoute,
  AdminDmcaRoute: AdminDmcaRoute,
  AdminImportRoute: AdminImportRoute,
  AdminRobiulRoute: AdminRobiulRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWriteRoute: AdminWriteRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminFakeReviewsOrderIdRoute: AdminFakeReviewsOrderIdRoute,
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  AdminPolicyOrderIdRoute: AdminPolicyOrderIdRoute,
  AdminPolicyTrainingRoute: AdminPolicyTrainingRoute,
  AdminFakeReviewsIndexRoute: AdminFakeReviewsIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminPolicyIndexRoute: AdminPolicyIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppDmcaRoute: typeof AppDmcaRoute
  AppGuideRoute: typeof AppGuideRoute
  AppPostRoute: typeof AppPostRoute
  AppProfilesRoute: typeof AppProfilesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppFakeReviewsOrderIdRoute: typeof AppFakeReviewsOrderIdRoute
  AppOrdersOrderIdRoute: typeof AppOrdersOrderIdRoute
  AppPolicyOrderIdRoute: typeof AppPolicyOrderIdRoute
  AppFakeReviewsIndexRoute: typeof AppFakeReviewsIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppPolicyIndexRoute: typeof AppPolicyIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDmcaRoute: AppDmcaRoute,
  AppGuideRoute: AppGuideRoute,
  AppPostRoute: AppPostRoute,
  AppProfilesRoute: AppProfilesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppFakeReviewsOrderIdRoute: AppFakeReviewsOrderIdRoute,
  AppOrdersOrderIdRoute: AppOrdersOrderIdRoute,
  AppPolicyOrderIdRoute: AppPolicyOrderIdRoute,
  AppFakeReviewsIndexRoute: AppFakeReviewsIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppPolicyIndexRoute: AppPolicyIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  XrpuasLogRoute: XrpuasLogRoute,
  ProfileSlugReviewSlugRoute: ProfileSlugReviewSlugRoute,
  BenediktHerrmannSlugRoute: BenediktHerrmannSlugRoute,
  BenediktHerrmannIndexInfoRoute: BenediktHerrmannIndexInfoRoute,
  JonasWeberSlugRoute: JonasWeberSlugRoute,
  JonasWeberIndexInfoRoute: JonasWeberIndexInfoRoute,
  AfridiSlugRoute: AfridiSlugRoute,
  AfridiIndexInfoRoute: AfridiIndexInfoRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  RobiulAlamSlugRoute: RobiulAlamSlugRoute,
  RobiulAlamIndexInfoRoute: RobiulAlamIndexInfoRoute,
  ProfileSlugIndexRoute: ProfileSlugIndexRoute,
  BenediktHerrmannIndexRoute: BenediktHerrmannIndexRoute,
  JonasWeberIndexRoute: JonasWeberIndexRoute,
  AfridiIndexRoute: AfridiIndexRoute,
  RobiulAlamIndexRoute: RobiulAlamIndexRoute,
  JordanReviewsSlugRoute: JordanReviewsSlugRoute,
  JordanReviewsIndexInfoRoute: JordanReviewsIndexInfoRoute,
  UHandleSlugRoute: UHandleSlugRoute,
  JordanReviewsIndexRoute: JordanReviewsIndexRoute,
  UHandleIndexRoute: UHandleIndexRoute,
  ApiPublicDmcaConfirmRoute: ApiPublicDmcaConfirmRoute,
  ApiPublicDmcaConfirmSingleRoute: ApiPublicDmcaConfirmSingleRoute,
  ApiPublicDmcaNextBatchRoute: ApiPublicDmcaNextBatchRoute,
  ApiPublicDmcaNextSingleRoute: ApiPublicDmcaNextSingleRoute,
  ApiPublicDmcaOrdersRoute: ApiPublicDmcaOrdersRoute,
  ApiPublicDmcaReleaseRoute: ApiPublicDmcaReleaseRoute,
  ApiPublicDmcaReleaseSingleRoute: ApiPublicDmcaReleaseSingleRoute,
  ApiPublicFakeReviewsCaptureRoute: ApiPublicFakeReviewsCaptureRoute,
  ApiPublicFakeReviewsDripTickRoute: ApiPublicFakeReviewsDripTickRoute,
  ApiPublicFakeReviewsSessionRoute: ApiPublicFakeReviewsSessionRoute,
  ApiPublicPolicyExtensionConfirmRoute: ApiPublicPolicyExtensionConfirmRoute,
  ApiPublicPolicyExtensionNextRoute: ApiPublicPolicyExtensionNextRoute,
  ApiPublicPolicyExtensionOrdersRoute: ApiPublicPolicyExtensionOrdersRoute,
  ApiPublicPolicyExtensionReleaseRoute: ApiPublicPolicyExtensionReleaseRoute,
  ApiPublicProfilesNextTargetRoute: ApiPublicProfilesNextTargetRoute,
  ApiPublicProfilesOrdersRoute: ApiPublicProfilesOrdersRoute,
  ApiPublicProfilesSubmitTargetRoute: ApiPublicProfilesSubmitTargetRoute,
  ApiPublicReviewImageSplatRoute: ApiPublicReviewImageSplatRoute,
  ApiPublicUserDmcaConfirmRoute: ApiPublicUserDmcaConfirmRoute,
  ApiPublicUserDmcaConfirmSingleRoute: ApiPublicUserDmcaConfirmSingleRoute,
  ApiPublicUserDmcaNextBatchRoute: ApiPublicUserDmcaNextBatchRoute,
  ApiPublicUserDmcaNextSingleRoute: ApiPublicUserDmcaNextSingleRoute,
  ApiPublicUserDmcaOrdersRoute: ApiPublicUserDmcaOrdersRoute,
  ApiPublicUserDmcaReleaseRoute: ApiPublicUserDmcaReleaseRoute,
  ApiPublicUserDmcaReleaseSingleRoute: ApiPublicUserDmcaReleaseSingleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
